services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mail-service
    ports:
      - "4567:4567"
    env_file:
      - .env
    restart: always
    networks:
      - health-management_health-management-network
networks:
  health-management_health-management-network:
    external: true
