POST http://localhost:4567/api/v1/mail/verify_code
Content-Type: application/json

{
  "email": "nguyenducduypc160903@gmail.com"
}

###
POST https://api.duynguyendev.xyz/api/v1/mail/verify_code
Content-Type: application/json

{
  "email": "nguyenducduypc160903@gmail.com"
}

###
POST https://api.duynguyendev.xyz/api/v1/mail/validate_code
Content-Type: application/json

{
  "email": "nguyenducduypc160903@gmail.com",
  "code": "645c2434"
}

###
GET https://api.duynguyendev.xyz/api/v1/mail/health
