POST http://127.0.0.1:4567/verify_code
Content-Type: application/json

{
  "email": "nguyenducduypc160903@gmail.com"
}

###
POST http://127.0.0.1:4567/validate_code
Content-Type: application/json

{
  "email": "nguyenducduypc160903@gmail.com",
  "code": "7ac57241"
}

###
GET http://localhost:4567/health
