POST http://localhost:4567/verify_code
Content-Type: application/json

{
  "email": "nguyenducduypc160903@gmail.com"
}

###
POST http://localhost:4567/validate_code
Content-Type: application/json

{
  "email": "nguyenducduypc160903@gmail.com",
  "code": "908ba141"
}

###
GET http://localhost:4567/health
